name 'elkserver'
maintainer 'Joel'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elkserver'
long_description 'Installs/Configures elkserver'
version '0.1.0'

#depends 'elk'
depends 'elkstack'
